#include "stdafx.h"
#include "OgreExports.h"
#include "luabind/luabind.hpp"
#include "luabind/operator.hpp"
#include "luabind/wrapper_base.hpp"
#include "luabind/class.hpp"
#include "luabind/adopt_policy.hpp"
#include "luabind/table_policy.hpp"

#include "Ogre.h"
#include "OgreMath.h"
#include "OgreEntity.h"
#include "OgreMovableObject.h"
#include "OgreSceneManager.h"
#include "OgreRenderTarget.h"
#include "OgreRenderWindow.h"
#include "OgreRenderable.h"
#include "OgreRenderTexture.h"
#include "OgreCamera.h"
#include "OgreViewport.h"
#include "OgreLight.h"
#include "OgreNode.h"
#include "OgreSceneNode.h"

namespace scripting
{
	void OgreExports::extendState(lua_State* pState)
	{
		luabind::module(pState, "Ogre")
				[
					luabind::class_<Ogre::Camera>("Camera")
				.def("getViewport", &Ogre::Camera::getViewport)
				.def("getViewMatrix", (const Ogre::Matrix4& (Ogre::Camera::*) (bool) const)&Ogre::Camera::getViewMatrix)
				.def("getViewMatrix", (const Ogre::Matrix4& (Ogre::Camera::*)(void)const)&Ogre::Camera::getViewMatrix)
				.def("getProjectionMatrix", &Ogre::Camera::getProjectionMatrix)				
				.def("getNearClipDistance", &Ogre::Camera::getNearClipDistance)
				.def("getFarClipDistance", &Ogre::Camera::getFarClipDistance)
				.def("setUseRenderingDistance", &Ogre::Camera::setUseRenderingDistance)
				.def("getUseRenderingDistance", &Ogre::Camera::getUseRenderingDistance)
				.def("setUseMinPixelSize", &Ogre::Camera::setUseMinPixelSize)
				.def("getUseMinPixelSize", &Ogre::Camera::getUseMinPixelSize)
				.def("getPixelDisplayRatio", &Ogre::Camera::getPixelDisplayRatio)
				.def("getAutoAspectRatio", &Ogre::Camera::getAutoAspectRatio)
				.def("getAspectRatio", &Ogre::Camera::getAspectRatio)
				.def("setAspectRatio", &Ogre::Camera::setAspectRatio)
				.def("getFOVy", &Ogre::Camera::getFOVy)				
				.def("setAutoAspectRatio", &Ogre::Camera::setAutoAspectRatio)
				.def("getAutoTrackTarget", &Ogre::Camera::getAutoTrackTarget)
				.def("setAutoTracking", &Ogre::Camera::setAutoTracking)
				.def("setWindow", &Ogre::Camera::setWindow)
				.def("resetWindow", &Ogre::Camera::resetWindow)
				.def("isWindowSet", &Ogre::Camera::isWindowSet)
				.def("setLodBias", &Ogre::Camera::setLodBias)
				.def("getLodBias", &Ogre::Camera::getLodBias)
				.def("getOrientation", &Ogre::Camera::getOrientation)
				.def("setOrientation", &Ogre::Camera::setOrientation)
				.def("setFixedYawAxis", &Ogre::Camera::setFixedYawAxis)
				.def("pitch", &Ogre::Camera::pitch)
				.def("yaw", &Ogre::Camera::yaw)
				.def("roll", &Ogre::Camera::roll)
				.def("move", &Ogre::Camera::move)
				.def("moveRelative", &Ogre::Camera::moveRelative)
				.def("getSceneManager", &Ogre::Camera::getSceneManager),

				luabind::class_<Ogre::Viewport>("Viewport")
				.def("getHeight", &Ogre::Viewport::getHeight)
				.def("getWidth", &Ogre::Viewport::getWidth)
				.def("getActualHeight", &Ogre::Viewport::getActualHeight)
				.def("getActualWidth", &Ogre::Viewport::getActualWidth)
				.def("getActualLeft", &Ogre::Viewport::getActualLeft)
				.def("getActualTop", &Ogre::Viewport::getActualTop)
				.def("getTop", &Ogre::Viewport::getTop)
				.def("getLeft", &Ogre::Viewport::getLeft)
				.def("setDimensions", &Ogre::Viewport::setDimensions)
				.def("getBackgroundColour", &Ogre::Viewport::getBackgroundColour)
				.def("setBackgroundColour", &Ogre::Viewport::setBackgroundColour)
				.def("getZOrder", &Ogre::Viewport::getZOrder)
				.def("getClearEveryFrame", &Ogre::Viewport::getClearEveryFrame)
				.def("getCamera", &Ogre::Viewport::getCamera)
				.def("getMaterialScheme", &Ogre::Viewport::getMaterialScheme)
				.def("setMaterialScheme", &Ogre::Viewport::setMaterialScheme)
				.def("getVisibilityMask", &Ogre::Viewport::getVisibilityMask)
				.def("setVisibilityMask", &Ogre::Viewport::setVisibilityMask)
				.def("setOverlaysEnabled", &Ogre::Viewport::setOverlaysEnabled)
				.def("getOverlaysEnabled", &Ogre::Viewport::getOverlaysEnabled),

				luabind::class_<Ogre::Node>("Node")
				.def("getName", &Ogre::Node::getName)
				.def("_getDerivedOrientation", &Ogre::Node::_getDerivedOrientation)
				.def("_getDerivedPosition", &Ogre::Node::_getDerivedPosition)
				.def("_getDerivedScale", &Ogre::Node::_getDerivedScale)
				.def("_getFullTransform", &Ogre::Node::_getFullTransform)
				.def("_setDerivedOrientation", &Ogre::Node::_setDerivedOrientation)
				.def("_setDerivedPosition", &Ogre::Node::_setDerivedPosition)
				.def("getParent", &Ogre::Node::getParent)
				.def("getOrientation", &Ogre::Node::getOrientation)
				.def("resetOrientation", &Ogre::Node::resetOrientation)
				.def("getScale", &Ogre::Node::getScale)
				.def("setScale", (void(Ogre::Node::*)(Ogre::Real,Ogre::Real,Ogre::Real))&Ogre::Node::setScale)
				.def("setScale", (void(Ogre::Node::*)(const Ogre::Vector3&))&Ogre::Node::setScale)
				.def("setPosition", (void(Ogre::Node::*)(Ogre::Real,Ogre::Real,Ogre::Real))&Ogre::Node::setPosition)
				.def("setPosition", (void(Ogre::Node::*)(const Ogre::Vector3&))&Ogre::Node::setPosition)
				.def("addChild", &Ogre::Node::addChild)
				.def("removeChild", (Ogre::Node*(Ogre::Node::*)(Ogre::Node*))&Ogre::Node::removeChild)
				.def("removeChild", (Ogre::Node*(Ogre::Node::*)(const Ogre::String&))&Ogre::Node::removeChild)
				.def("removeAllChildren", &Ogre::Node::removeAllChildren)
				.def("getPosition", &Ogre::Node::getPosition)
				.def("setInheritOrientation", &Ogre::Node::setInheritOrientation)
				.def("setInheritScale", &Ogre::Node::setInheritScale)
				.def("yaw", &Ogre::Node::yaw)
				.def("roll", &Ogre::Node::roll)
				.def("pitch", &Ogre::Node::pitch),

				luabind::class_<Ogre::SceneNode, luabind::bases<Ogre::Node> >("SceneNode")
				.def("attachObject", &Ogre::SceneNode::attachObject)
				.def("numAttachedObjects", &Ogre::SceneNode::numAttachedObjects)
				.def("getAttachedObjectByIndex", (Ogre::MovableObject*(Ogre::SceneNode::*)(unsigned short))&Ogre::SceneNode::getAttachedObject)
				.def("getAttachedObjectByName", (Ogre::MovableObject*(Ogre::SceneNode::*)(const Ogre::String&))&Ogre::SceneNode::getAttachedObject)
				.def("detachObjectByName", (Ogre::MovableObject*(Ogre::SceneNode::*)(const Ogre::String&))&Ogre::SceneNode::detachObject)
				.def("detachObjectByIndex", (Ogre::MovableObject*(Ogre::SceneNode::*)(unsigned short))&Ogre::SceneNode::detachObject)				
				.def("detachAllObjects", &Ogre::SceneNode::detachAllObjects)
				.def("isInSceneGraph", &Ogre::SceneNode::isInSceneGraph)
				.def("_update", &Ogre::SceneNode::_update)
				.def("_updateBounds", &Ogre::SceneNode::_updateBounds)
				.def("removeAndDestroyChildByName", (void(Ogre::SceneNode::*)(const Ogre::String&))&Ogre::SceneNode::removeAndDestroyChild)
				.def("removeAndDestroyChildByIndex", (void(Ogre::SceneNode::*)(unsigned short))&Ogre::SceneNode::removeAndDestroyChild)
				.def("removeAndDestroyAllChildren", &Ogre::SceneNode::removeAndDestroyAllChildren)
				.def("showBoundingBox", &Ogre::SceneNode::showBoundingBox)
				.def("hideBoundingBox", &Ogre::SceneNode::hideBoundingBox)
				.def("getShowBoundingBox", &Ogre::SceneNode::getShowBoundingBox)
				.def("createChildSceneNode", (Ogre::SceneNode*(Ogre::SceneNode::*)(const Ogre::Vector3&, const Ogre::Quaternion&))&Ogre::SceneNode::createChildSceneNode)
				.def("createChildSceneNodeWithName", (Ogre::SceneNode*(Ogre::SceneNode::*)(const Ogre::String&, const Ogre::Vector3&, const Ogre::Quaternion&))&Ogre::SceneNode::createChildSceneNode)
				.def("setFixedYawAxis", &Ogre::SceneNode::setFixedYawAxis)
				.def("lookAt", &Ogre::SceneNode::lookAt)
				.def("getParentSceneNode", &Ogre::SceneNode::getParentSceneNode)
				.def("setVisible", &Ogre::SceneNode::setVisible)
				.def("flipVisibility", &Ogre::SceneNode::flipVisibility)
				.def("setDebugDisplayEnabled", &Ogre::SceneNode::setDebugDisplayEnabled)
				.def("getCreator", &Ogre::SceneNode::getCreator),	

				luabind::class_<Ogre::ColourValue>("ColourValue")
				.def(luabind::constructor<float, float, float, float>())
				.def("getAsRGBA", &Ogre::ColourValue::getAsRGBA)
				.def("getAsARGB", &Ogre::ColourValue::getAsARGB)
				.def("getAsBGRA", &Ogre::ColourValue::getAsBGRA)
				.def("getAsABGR", &Ogre::ColourValue::getAsABGR)
				.def("setAsRGBA", &Ogre::ColourValue::setAsRGBA)
				.def("setAsARGB", &Ogre::ColourValue::setAsARGB)
				.def("setAsBGRA", &Ogre::ColourValue::setAsBGRA)
				.def("setAsABGR", &Ogre::ColourValue::setAsABGR)
				.def("saturate", &Ogre::ColourValue::saturate)
				.def("saturateCopy", &Ogre::ColourValue::saturateCopy)
				.def("setHSB", &Ogre::ColourValue::setHSB)
				.def("getHSB", &Ogre::ColourValue::getHSB)
				.def_readwrite( "r", &Ogre::ColourValue::r )
				.def_readwrite( "g", &Ogre::ColourValue::g )
				.def_readwrite( "b", &Ogre::ColourValue::b )
				.def_readwrite( "a", &Ogre::ColourValue::a )
				.def(luabind::self / luabind::other<Ogre::ColourValue>())
				.def(luabind::self / luabind::other<float>())
				.def(luabind::self * luabind::other<Ogre::ColourValue>())
				.def(luabind::self * luabind::other<float>())
				.def(luabind::self + luabind::other<Ogre::ColourValue>())
				.def(luabind::self - luabind::other<Ogre::ColourValue>())
				.def(luabind::self == luabind::other<Ogre::ColourValue>()),

				luabind::class_<Ogre::MovableObject>("MovableObject")
				.def("isVisible", &Ogre::MovableObject::isVisible)
				.def("getName", &Ogre::MovableObject::getName)
				.def("getMovableType", &Ogre::MovableObject::getMovableType)
				.def("getParentNode", &Ogre::MovableObject::getParentNode)
				.def("setCastShadows", &Ogre::MovableObject::setCastShadows)
				.def("getCastShadows", &Ogre::MovableObject::getCastShadows),				

				luabind::class_<Ogre::SubEntity>("SubEntity")
				.def("getMaterialName", &Ogre::SubEntity::getMaterialName)
				.def("setMaterialName", &Ogre::SubEntity::setMaterialName)
				.def("setMaterial", &Ogre::SubEntity::setMaterial)
				.def("setVisible", &Ogre::SubEntity::setVisible)
				.def("isVisible", &Ogre::SubEntity::isVisible)
				.def("getSubMesh", &Ogre::SubEntity::getSubMesh)
				.def("getParent", &Ogre::SubEntity::getParent)
				.def("getMaterial", &Ogre::SubEntity::getMaterial)
				.def("getTechnique", &Ogre::SubEntity::getTechnique)
				.def("getRenderOperation", &Ogre::SubEntity::getRenderOperation)
				.def("getWorldTransforms", &Ogre::SubEntity::getWorldTransforms)
				.def("getNumWorldTransforms", &Ogre::SubEntity::getNumWorldTransforms)
				.def("getSquaredViewDepth", &Ogre::SubEntity::getSquaredViewDepth)
				.def("getLights", &Ogre::SubEntity::getLights)
				.def("getCastsShadows", &Ogre::SubEntity::getCastsShadows)
				.def("setCustomParameter", (void(Ogre::SubEntity::*)(size_t, const Ogre::Vector4&))&Ogre::SubEntity::setCustomParameter)
                .def("getCustomParameter", &Ogre::SubEntity::getCustomParameter)
				.def("_updateCustomGpuParameter", &Ogre::SubEntity::_updateCustomGpuParameter),
				
				luabind::class_<Ogre::Entity, luabind::bases<Ogre::MovableObject> >("Entity")
				.def("getMesh", &Ogre::Entity::getMesh)
				.def("getSubEntity", (Ogre::SubEntity*(Ogre::Entity::*)(unsigned int) const)&Ogre::Entity::getSubEntity)
				.def("getSubEntityByName", (Ogre::SubEntity*(Ogre::Entity::*)(const Ogre::String&) const)&Ogre::Entity::getAllAnimationStates)
				.def("getNumSubEntities", &Ogre::Entity::getNumSubEntities)
				.def("clone", &Ogre::Entity::clone)
				.def("setCastShadows", &Ogre::Entity::setCastShadows)
				.def("setMaterialName", &Ogre::Entity::setMaterialName)
				.def("setMaterial", &Ogre::Entity::setMaterial)
				.def("setRenderQueueGroup", &Ogre::Entity::setRenderQueueGroup)
				.def("setRenderQueueGroupAndPriority", &Ogre::Entity::setRenderQueueGroupAndPriority)
				.def("getBoundingBox", &Ogre::Entity::getBoundingBox)
				.def("getChildObjectsBoundingBox", &Ogre::Entity::getChildObjectsBoundingBox)
				.def("getMovableType", &Ogre::Entity::getMovableType)
				.def("getAnimationState", &Ogre::Entity::getAnimationState)
				.def("getAllAnimationStates", &Ogre::Entity::getAllAnimationStates)
				.def("setDisplaySkeleton", &Ogre::Entity::setDisplaySkeleton)
				.def("getDisplaySkeleton", &Ogre::Entity::getDisplaySkeleton)
				.def("getNumManualLodLevels", &Ogre::Entity::getNumManualLodLevels)
				.def("getCurrentLodIndex", &Ogre::Entity::getCurrentLodIndex)
				.def("getManualLodLevel", &Ogre::Entity::getManualLodLevel)
				.def("setMeshLodBias", &Ogre::Entity::setMeshLodBias)
				.def("setMaterialLodBias", &Ogre::Entity::setMaterialLodBias)
				.def("getName", &Ogre::Entity::getName)
				.def("setPolygonModeOverrideable", &Ogre::Entity::setPolygonModeOverrideable),

				luabind::class_<Ogre::ManualObject::ManualObjectSection>("ManualObjectSection")
				.def("getMaterialName", &Ogre::ManualObject::ManualObjectSection::getMaterialName)
				.def("getMaterialGroup", &Ogre::ManualObject::ManualObjectSection::getMaterialGroup)
				.def("setMaterialName", &Ogre::ManualObject::ManualObjectSection::setMaterialName),				                
			
				luabind::class_<Ogre::ManualObject, luabind::bases<Ogre::MovableObject> >("ManualObject")
				.def("clear", &Ogre::ManualObject::clear)
				.def("estimateVertexCount", &Ogre::ManualObject::estimateVertexCount)
				.def("estimateIndexCount", &Ogre::ManualObject::estimateIndexCount)
				.def("beginOp", &Ogre::ManualObject::begin)
				.def("quad", &Ogre::ManualObject::quad)
				.def("setDynamic", &Ogre::ManualObject::setDynamic)
				.def("getDynamic", &Ogre::ManualObject::getDynamic)
				.def("beginUpdate", &Ogre::ManualObject::beginUpdate)
				.def("position", (void(Ogre::ManualObject::*)(const Ogre::Vector3&))&Ogre::ManualObject::position)
				.def("positionXYZ", (void(Ogre::ManualObject::*)(Ogre::Real, Ogre::Real, Ogre::Real))&Ogre::ManualObject::position)
				.def("normal", (void(Ogre::ManualObject::*)(const Ogre::Vector3&))&Ogre::ManualObject::normal)
				.def("normalXYZ", (void(Ogre::ManualObject::*)(Ogre::Real, Ogre::Real, Ogre::Real))&Ogre::ManualObject::normal)
				.def("textureCoordX", (void(Ogre::ManualObject::*)(Ogre::Real))&Ogre::ManualObject::textureCoord)
				.def("textureCoordXY", (void(Ogre::ManualObject::*)(Ogre::Real,Ogre::Real))&Ogre::ManualObject::textureCoord)
				.def("textureCoordXYZ", (void(Ogre::ManualObject::*)(Ogre::Real, Ogre::Real, Ogre::Real))&Ogre::ManualObject::textureCoord)
				.def("textureCoordXYZW", (void(Ogre::ManualObject::*)(Ogre::Real,Ogre::Real,Ogre::Real,Ogre::Real))&Ogre::ManualObject::textureCoord)
				.def("textureCoord2dVec", (void(Ogre::ManualObject::*)(const Ogre::Vector2&))&Ogre::ManualObject::textureCoord)
				.def("textureCoord3dVec", (void(Ogre::ManualObject::*)(const Ogre::Vector3&))&Ogre::ManualObject::textureCoord)
				.def("textureCoord4dVec", (void(Ogre::ManualObject::*)(const Ogre::Vector4&))&Ogre::ManualObject::textureCoord)
				.def("colourRGBA", (void(Ogre::ManualObject::*)(Ogre::Real,Ogre::Real,Ogre::Real,Ogre::Real))&Ogre::ManualObject::colour)
				.def("colour", (void(Ogre::ManualObject::*)(const Ogre::ColourValue&))&Ogre::ManualObject::colour)
				.def("index", &Ogre::ManualObject::index)
				.def("triangle", &Ogre::ManualObject::triangle)
				.def("quad", &Ogre::ManualObject::quad)
				.def("endOp", &Ogre::ManualObject::end)
				.def("setMaterialName", &Ogre::ManualObject::setMaterialName)
				.def("convertToMesh", &Ogre::ManualObject::convertToMesh)
				.def("setUseIdentityProjection", &Ogre::ManualObject::setUseIdentityProjection)
				.def("getUseIdentityProjection", &Ogre::ManualObject::getUseIdentityProjection)
				.def("setUseIdentityView", &Ogre::ManualObject::setUseIdentityView)
				.def("getUseIdentityView", &Ogre::ManualObject::getUseIdentityView)
				.def("setBoundingBox", &Ogre::ManualObject::setBoundingBox)
				.def("getSection", &Ogre::ManualObject::getSection)
				.def("getNumSections", &Ogre::ManualObject::getNumSections)
				.def("setKeepDeclarationOrder", &Ogre::ManualObject::setKeepDeclarationOrder)
				.def("getKeepDeclarationOrder", &Ogre::ManualObject::getKeepDeclarationOrder)
				.def("getMovableType", &Ogre::ManualObject::getMovableType)
				.def("getBoundingBox", &Ogre::ManualObject::getBoundingBox)
				.def("getBoundingRadius", &Ogre::ManualObject::getBoundingRadius),

				luabind::class_<Ogre::RenderTarget>("RenderTarget")
				.def("getWidth", &Ogre::RenderTarget::getWidth)
				.def("getHeight", &Ogre::RenderTarget::getHeight)
				.def("getColourDepth", &Ogre::RenderTarget::getColourDepth)
				.def("update", &Ogre::RenderTarget::update)
				.def("removeAllViewports", &Ogre::RenderTarget::removeAllViewports)
				.def("removeViewport", &Ogre::RenderTarget::removeViewport)
				.def("addViewport", &Ogre::RenderTarget::addViewport)
				.def("getNumViewports", &Ogre::RenderTarget::getNumViewports)
				.def("getViewport", &Ogre::RenderTarget::getViewport)
				.def("hasViewportWithZOrder", &Ogre::RenderTarget::hasViewportWithZOrder)
				.def("getViewportByZOrder", &Ogre::RenderTarget::getViewportByZOrder)
				.def("getName", &Ogre::RenderTarget::getName),

				luabind::class_<Ogre::RenderWindow, luabind::bases<Ogre::RenderTarget> >("RenderWindow")
				.def("setVisible", &Ogre::RenderWindow::setVisible)
				.def("isVisible", &Ogre::RenderWindow::isVisible)
				.def("isFullScreen", &Ogre::RenderWindow::isFullScreen)
				.def("getAverageFPS", &Ogre::RenderWindow::getAverageFPS)
				.def("getLastFPS", &Ogre::RenderWindow::getLastFPS)
				.def("getBestFPS", &Ogre::RenderWindow::getBestFPS)
				.def("getBestFrameTime", &Ogre::RenderWindow::getBestFrameTime)
				.def("getWorstFrameTime", &Ogre::RenderWindow::getWorstFrameTime)
				.def("getWorstFPS", &Ogre::RenderWindow::getWorstFPS)
				.def("getTriangleCount", &Ogre::RenderWindow::getTriangleCount)
				.def("getBatchCount", &Ogre::RenderWindow::getBatchCount)
				.def("getFSAA", &Ogre::RenderWindow::getFSAA)
				.def("getFSAAHint", &Ogre::RenderWindow::getFSAAHint)
				.def("getVSyncInterval", &Ogre::RenderWindow::getVSyncInterval)
				.def("isHidden", &Ogre::RenderWindow::isHidden)
				.def("isPrimary", &Ogre::RenderWindow::isPrimary)
				.def("reposition", &Ogre::RenderWindow::reposition)
				.def("setFullscreen", &Ogre::RenderWindow::setFullscreen)
				.def("setHidden", &Ogre::RenderWindow::setHidden)
				.def("setDeactivateOnFocusChange", &Ogre::RenderWindow::setDeactivateOnFocusChange)
				.def("resetStatistics", &Ogre::RenderWindow::resetStatistics)
				.def("windowMovedOrResized", &Ogre::RenderWindow::windowMovedOrResized)
				.def("resize", &Ogre::RenderWindow::resize)
				.def("writeContentsToFile", &Ogre::RenderWindow::writeContentsToFile)
				.def("writeContentsToTimestampedFile", &Ogre::RenderWindow::writeContentsToTimestampedFile),

				luabind::class_<Ogre::SceneManager>("SceneManager")
				.def("getName", &Ogre::SceneManager::getName)
				.def("getTypeName", &Ogre::SceneManager::getTypeName)
				.def("createCamera", &Ogre::SceneManager::createCamera)
				.def("getCamera", &Ogre::SceneManager::getCamera)
				.def("hasCamera", &Ogre::SceneManager::hasCamera)
				.def("destroyCamera", (void(Ogre::SceneManager::*)(Ogre::Camera*))&Ogre::SceneManager::destroyCamera)
				.def("destroyCameraByName", (void(Ogre::SceneManager::*)(const Ogre::String&))&Ogre::SceneManager::destroyCamera)
				.def("destroyAllCameras", &Ogre::SceneManager::destroyAllCameras)
				.def("createLightWithName", (Ogre::Light*(Ogre::SceneManager::*)(const Ogre::String&))&Ogre::SceneManager::createLight)
				.def("createLight", (Ogre::Light*(Ogre::SceneManager::*)(void))&Ogre::SceneManager::createLight)
				.def("getLight", &Ogre::SceneManager::getLight)
				.def("hasLight", &Ogre::SceneManager::hasLight)
				.def("destroyLight", (void(Ogre::SceneManager::*)(Ogre::Light*))&Ogre::SceneManager::destroyLight)
				.def("destroyLightByName", (void(Ogre::SceneManager::*)(const Ogre::String&))&Ogre::SceneManager::destroyLight)
				.def("destroyAllLights", &Ogre::SceneManager::destroyAllLights)
				.def("createSceneNode", (Ogre::SceneNode*(Ogre::SceneManager::*)(void))&Ogre::SceneManager::createSceneNode)
				.def("createSceneNodeWithName", (Ogre::SceneNode*(Ogre::SceneManager::*)(const Ogre::String&))&Ogre::SceneManager::createSceneNode)
				.def("destroySceneNodeByName", (void(Ogre::SceneManager::*)(const Ogre::String&))&Ogre::SceneManager::destroySceneNode)
				.def("destroySceneNode", (void(Ogre::SceneManager::*)(Ogre::SceneNode*))&Ogre::SceneManager::destroySceneNode)
				.def("getRootSceneNode", &Ogre::SceneManager::getRootSceneNode)
				.def("getSceneNode", &Ogre::SceneManager::getSceneNode)
				.def("hasSceneNode", &Ogre::SceneManager::hasSceneNode)
				.def("createEntity", (Ogre::Entity*(Ogre::SceneManager::*)(const Ogre::String&, const Ogre::String&, const Ogre::String&))&Ogre::SceneManager::createEntity)
				.def("getEntity", &Ogre::SceneManager::getEntity)
				.def("hasEntity", &Ogre::SceneManager::hasEntity)
				.def("destroyEntityByName", (void(Ogre::SceneManager::*)(const Ogre::String&))&Ogre::SceneManager::destroyEntity)
				.def("destroyEntity", (void(Ogre::SceneManager::*)(Ogre::Entity*))&Ogre::SceneManager::destroyEntity)
				.def("destroyAllEntities", &Ogre::SceneManager::destroyAllEntities)
				.def("createManualObjectWithName", (Ogre::ManualObject*(Ogre::SceneManager::*)(const Ogre::String&))&Ogre::SceneManager::createManualObject)
				.def("createManualObject", (Ogre::ManualObject*(Ogre::SceneManager::*)(void))&Ogre::SceneManager::createManualObject)
				.def("hasManualObject", &Ogre::SceneManager::hasManualObject)
				.def("destroyManualObject", (void(Ogre::SceneManager::*)(Ogre::ManualObject*))&Ogre::SceneManager::destroyManualObject)
				.def("destroyManualObjectByName", (void(Ogre::SceneManager::*)(const Ogre::String&))&Ogre::SceneManager::destroyManualObject)
				.def("destroyAllManualObjects", &Ogre::SceneManager::destroyAllManualObjects)
				.def("createBillboardChainWithName", (Ogre::BillboardChain*(Ogre::SceneManager::*)(const Ogre::String&))&Ogre::SceneManager::createBillboardChain)
				.def("createBillboardChain", (Ogre::BillboardChain*(Ogre::SceneManager::*)(void))&Ogre::SceneManager::createBillboardChain)
				.def("getBillboardChain", &Ogre::SceneManager::getBillboardChain)
				.def("hasBillboardChain", &Ogre::SceneManager::hasBillboardChain)
				.def("destroyBillboardChain", (void(Ogre::SceneManager::*)(Ogre::BillboardChain*))&Ogre::SceneManager::destroyBillboardChain)
				.def("destroyBillboardChainByName", (void(Ogre::SceneManager::*)(const Ogre::String&))&Ogre::SceneManager::destroyBillboardChain)
				.def("destroyAllBillboardChains", &Ogre::SceneManager::destroyAllBillboardChains)
				.def("createRibbonTrailWithName", (Ogre::RibbonTrail*(Ogre::SceneManager::*)(const Ogre::String&))&Ogre::SceneManager::createRibbonTrail)
				.def("createRibbonTrail", (Ogre::RibbonTrail*(Ogre::SceneManager::*)(void))&Ogre::SceneManager::createRibbonTrail)
				.def("getRibbonTrail", &Ogre::SceneManager::getRibbonTrail)
				.def("hasRibbonTrail", &Ogre::SceneManager::hasRibbonTrail)
				.def("destroyRibbonTrail", (void(Ogre::SceneManager::*)(Ogre::RibbonTrail*))&Ogre::SceneManager::destroyRibbonTrail)
				.def("destroyRibbonTrailByName", (void(Ogre::SceneManager::*)(const Ogre::String&))&Ogre::SceneManager::destroyRibbonTrail)
				.def("destroyAllRibbonTrails", &Ogre::SceneManager::destroyAllRibbonTrails)
				.def("createParticleSystem", (Ogre::ParticleSystem*(Ogre::SceneManager::*)(const Ogre::String&, const Ogre::String&))&Ogre::SceneManager::createParticleSystem)
				.def("createParticleSystemWithMaxQuata", (Ogre::ParticleSystem*(Ogre::SceneManager::*)(const Ogre::String&, size_t, const Ogre::String&))&Ogre::SceneManager::createParticleSystem)
				.def("getParticleSystem", &Ogre::SceneManager::getParticleSystem)
				.def("hasParticleSystem", &Ogre::SceneManager::hasParticleSystem)
				.def("destroyParticleSystem", (void(Ogre::SceneManager::*)(Ogre::ParticleSystem*))&Ogre::SceneManager::destroyParticleSystem)
				.def("destroyParticleSystemByName", (void(Ogre::SceneManager::*)(const Ogre::String&))&Ogre::SceneManager::destroyParticleSystem)
				.def("destroyAllParticleSystems", &Ogre::SceneManager::destroyAllParticleSystems)
				.def("clearScene", &Ogre::SceneManager::clearScene)
				.def("setAmbientLight", &Ogre::SceneManager::setAmbientLight)
				.def("getAmbientLight", &Ogre::SceneManager::getAmbientLight)
				.def("setOption", &Ogre::SceneManager::setOption)
				.def("getOption", &Ogre::SceneManager::getOption)
				.def("hasOption", &Ogre::SceneManager::hasOption)
				.def("setFog", &Ogre::SceneManager::setFog)
				.def("getFogMode", &Ogre::SceneManager::getFogMode)
				.def("getFogColour", &Ogre::SceneManager::getFogColour)
				.def("getFogStart", &Ogre::SceneManager::getFogStart)
				.def("getFogEnd", &Ogre::SceneManager::getFogEnd)
				.def("getFogDensity", &Ogre::SceneManager::getFogDensity)
				.def("createBillboardSetByName", (Ogre::BillboardSet*(Ogre::SceneManager::*)(const Ogre::String&, unsigned int))&Ogre::SceneManager::createBillboardSet)
				.def("createBillboardSet", (Ogre::BillboardSet*(Ogre::SceneManager::*)(unsigned int))&Ogre::SceneManager::createBillboardSet)
				.def("getBillboardSet", &Ogre::SceneManager::getBillboardSet)
				.def("hasBillboardSet", &Ogre::SceneManager::hasBillboardSet)
				.def("destroyBillboardSet", (void(Ogre::SceneManager::*)(Ogre::BillboardSet*))&Ogre::SceneManager::destroyBillboardSet)
				.def("destroyBillboardSetByName", (void(Ogre::SceneManager::*)(const Ogre::String&))&Ogre::SceneManager::destroyBillboardSet)
				.def("destroyAllBillboardSets", &Ogre::SceneManager::destroyAllBillboardSets)
				.def("setDisplaySceneNodes", &Ogre::SceneManager::setDisplaySceneNodes)
				.def("getDisplaySceneNodes", &Ogre::SceneManager::getDisplaySceneNodes)
				.def("showBoundingBoxes", &Ogre::SceneManager::showBoundingBoxes)
				.def("getShowBoundingBoxes", &Ogre::SceneManager::getShowBoundingBoxes)
				.def("createStaticGeometry", &Ogre::SceneManager::createStaticGeometry)
				.def("getStaticGeometry", &Ogre::SceneManager::getStaticGeometry)
				.def("hasStaticGeometry", &Ogre::SceneManager::hasStaticGeometry)
				.def("destroyStaticGeometry", (void(Ogre::SceneManager::*)(Ogre::StaticGeometry*))&Ogre::SceneManager::destroyStaticGeometry)
				.def("destroyStaticGeometry", (void(Ogre::SceneManager::*)(const Ogre::String&))&Ogre::SceneManager::destroyStaticGeometry)
				.def("destroyAllStaticGeometry", &Ogre::SceneManager::destroyAllStaticGeometry)
				.enum_("RenderOperation")
				[
					luabind::value("OT_POINT_LIST", Ogre::RenderOperation::OT_POINT_LIST),
					luabind::value("OT_LINE_LIST", Ogre::RenderOperation::OT_LINE_LIST),
					luabind::value("OT_LINE_STRIP", Ogre::RenderOperation::OT_LINE_STRIP),
					luabind::value("OT_TRIANGLE_LIST", Ogre::RenderOperation::OT_TRIANGLE_LIST),
					luabind::value("OT_TRIANGLE_STRIP", Ogre::RenderOperation::OT_TRIANGLE_STRIP),
					luabind::value("OT_TRIANGLE_FAN", Ogre::RenderOperation::OT_TRIANGLE_FAN)

				]
			]; 
	}
}